import type { SeedEntity } from "./types";

export const SEED: SeedEntity[] = [
  // —— Labs ——————————————————————————————————————————————
  {
    id: "openai",
    kind: "lab",
    name: "OpenAI",
    tagline: "ChatGPT, GPT-5.6, Sora, and the largest consumer AI surface",
    description:
      "Operates ChatGPT (GPT-5.6 Sol/Terra/Luna since July 2026), Codex, Sora, and ChatGPT Images 2.0. Broadest ecosystem; default consumer assistant for most people.",
    license: "commercial",
    vendor: "OpenAI",
    website: "https://openai.com",
    github: "https://github.com/openai",
    categories: ["chat", "coding", "image", "video", "agents"],
    techniques: ["transformer", "moe", "rlhf", "test-time-compute", "tool-use"],
    features: ["ChatGPT", "API", "Codex", "Sora", "Images 2.0", "GPT Store"],
    pricing: "Free–$200/mo + API",
    catalog_weight: 96,
    aliases: ["openai", "chatgpt"],
    trend: 0.4,
  },
  {
    id: "anthropic",
    kind: "lab",
    name: "Anthropic",
    tagline: "Claude Opus 5 and Fable 5 — current intelligence and writing leaders",
    description:
      "Constitutional AI lab. Claude Opus 5 (24 Jul 2026) leads Artificial Analysis Intelligence (63) and Agentic (55.3) indices. Fable 5 leads Arena text. Claude Code and Cowork cover coding and desktop agents.",
    license: "commercial",
    vendor: "Anthropic",
    website: "https://www.anthropic.com",
    github: "https://github.com/anthropics",
    categories: ["chat", "coding", "agents", "research"],
    techniques: ["constitutional-ai", "rlhf", "tool-use", "computer-use", "test-time-compute"],
    features: ["Claude", "Claude Code", "Cowork", "API", "MCP apps"],
    pricing: "Free–$200/mo + API",
    catalog_weight: 97,
    aliases: ["anthropic", "claude"],
    trend: 1.6,
  },
  {
    id: "google-deepmind",
    kind: "lab",
    name: "Google DeepMind",
    tagline: "Gemini 3.1 Pro, Veo, Spark agents, and Google-native research",
    description:
      "Gemini 3.1 Pro leads several reasoning boards (GPQA, ARC-AGI-1). Veo / Omni Flash lead video. Gemini Spark is the 24/7 cloud agent. Deep integration with Search, Docs, Android.",
    license: "commercial",
    vendor: "Google",
    website: "https://deepmind.google",
    categories: ["chat", "research", "video", "agents"],
    techniques: ["transformer", "moe", "rag", "test-time-compute", "tool-use"],
    features: ["Gemini", "Veo", "Imagen", "Spark", "NotebookLM", "AI Overviews"],
    pricing: "Free–$19.99/mo + API",
    catalog_weight: 93,
    aliases: ["google", "deepmind", "gemini", "veo"],
    trend: 0.6,
  },
  {
    id: "xai",
    kind: "lab",
    name: "xAI",
    tagline: "Grok 4.6 — cheapest frontier-class model after the 12 Aug refresh",
    description:
      "Grok 4.6 (12 Aug 2026) is a post-training refresh of Grok 4.5: Intelligence Index 61, tying GPT-5.6 Sol at $2/$6 per 1M tokens, 500K context. Live in Grok, Cursor, Grok Build, OpenRouter.",
    license: "commercial",
    vendor: "xAI",
    website: "https://x.ai",
    categories: ["chat", "coding", "agents", "research"],
    techniques: ["moe", "rlhf", "test-time-compute", "tool-use", "multi-agent"],
    features: ["Grok", "Grok Build", "API", "Imagine", "X integration"],
    pricing: "Free–Premium+ + API $2/$6",
    catalog_weight: 94,
    aliases: ["xai", "x.ai", "grok", "spacexai"],
    trend: 2.8,
  },
  {
    id: "meta-ai",
    kind: "lab",
    name: "Meta AI",
    tagline: "Llama open-weights family and Meta AI assistant",
    description:
      "Releases the Llama open-weights line used as the default base for Western local and enterprise fine-tunes. Meta AI is the consumer assistant inside WhatsApp, Instagram, and Facebook.",
    license: "mixed",
    vendor: "Meta",
    website: "https://ai.meta.com",
    github: "https://github.com/meta-llama",
    categories: ["open-models", "chat", "local"],
    techniques: ["transformer", "moe", "lora", "quantization"],
    features: ["Llama weights", "Meta AI", "Purple Llama safety"],
    pricing: "Weights free (community license); assistant free",
    catalog_weight: 88,
    aliases: ["meta", "llama", "meta ai"],
    trend: 0.2,
  },
  {
    id: "deepseek",
    kind: "lab",
    name: "DeepSeek",
    tagline: "Open-weight reasoning models that reset the cost curve",
    description:
      "Hangzhou lab behind DeepSeek-V3 and R1. Open weights, aggressive pricing, and reasoning-first post-training that forced Western labs to cut API prices in 2025–26.",
    license: "open-source",
    vendor: "DeepSeek",
    website: "https://www.deepseek.com",
    github: "https://github.com/deepseek-ai",
    categories: ["open-models", "chat", "coding", "research"],
    techniques: ["moe", "grpo", "distillation", "quantization", "test-time-compute"],
    features: ["R1 reasoning", "V3 base", "cheap API", "open weights"],
    pricing: "Open weights + low-cost API",
    catalog_weight: 90,
    aliases: ["deepseek", "deepseek-r1", "deepseek-v3"],
    trend: 0.8,
  },
  {
    id: "mistral",
    kind: "lab",
    name: "Mistral AI",
    tagline: "European open-and-commercial mixtral lineage",
    description:
      "Paris lab shipping Mixtral-style MoE models, Mistral Large, and Le Chat. Strong European data-residency story and a dual open/commercial catalog.",
    license: "mixed",
    vendor: "Mistral AI",
    website: "https://mistral.ai",
    github: "https://github.com/mistralai",
    categories: ["open-models", "chat", "coding"],
    techniques: ["moe", "transformer", "quantization"],
    features: ["Le Chat", "La Plateforme", "open MoE weights"],
    pricing: "Free–Le Chat Pro + API",
    catalog_weight: 78,
    aliases: ["mistral", "mixtral"],
    trend: 0.1,
  },
  {
    id: "huggingface",
    kind: "lab",
    name: "Hugging Face",
    tagline: "The public square for models, datasets, papers, and inference",
    description:
      "Hub for 2M+ public models, Spaces, Inference Endpoints, TRL, Transformers, Diffusers, and daily trending papers. De-facto distribution layer for open-source AI.",
    license: "mixed",
    vendor: "Hugging Face",
    website: "https://huggingface.co",
    github: "https://github.com/huggingface",
    categories: ["infra", "open-models", "research"],
    techniques: ["lora", "quantization", "distillation", "rag"],
    features: ["Hub", "Spaces", "Inference", "TRL", "Transformers", "Papers"],
    pricing: "Free Hub; paid inference/enterprise",
    catalog_weight: 91,
    aliases: ["huggingface", "hugging face", "hf"],
    trend: 0.5,
  },

  // —— Models ——————————————————————————————————————————————
  {
    id: "claude-opus-5",
    kind: "model",
    name: "Claude Opus 5",
    tagline: "Anthropic flagship — AA Intelligence 63 at 24 Jul 2026 ship (cited, not live)",
    description:
      "Shipped 24 Jul 2026. Intelligence Index 63, Agentic Index 55.3, Arena WebDev and Agent boards #1. $5/$25 per 1M tokens with Fast and effort controls. Default on Claude Max.",
    license: "commercial",
    vendor: "Anthropic",
    website: "https://www.anthropic.com/claude",
    categories: ["chat", "coding", "agents", "research"],
    techniques: ["test-time-compute", "tool-use", "computer-use", "constitutional-ai"],
    features: ["Extended thinking", "Fast mode", "Effort slider", "Computer use", "128k output"],
    pricing: "$5 / $25 per 1M tokens",
    catalog_weight: 98,
    aliases: ["opus 5", "claude opus 5", "claude-opus-5"],
    trend: 1.8,
    verified: "2026-07-24",
    spec: { contextK: 200, priceIn: 5, priceOut: 25, selfHost: false },
  },
  {
    id: "claude-fable-5",
    kind: "model",
    name: "Claude Fable 5",
    tagline: "Writing and long-form leader on Arena text and HLE",
    description:
      "Anthropic’s prose specialist. #1 Arena text (~1508), Humanity’s Last Exam 53.3%, AA-Omniscience 40. Preferred when the output is meant to be read, not just executed.",
    license: "commercial",
    vendor: "Anthropic",
    website: "https://www.anthropic.com/claude",
    categories: ["chat", "research"],
    techniques: ["constitutional-ai", "test-time-compute", "rlhf"],
    features: ["Natural prose", "Long output", "Citations", "Artifacts"],
    pricing: "Claude Pro/Max + API",
    catalog_weight: 92,
    aliases: ["fable 5", "claude fable", "fable-5"],
    trend: 1.1,
    verified: "2026-07-24",
    spec: { contextK: 200, selfHost: false },
  },
  {
    id: "gpt-5.6",
    kind: "model",
    name: "GPT-5.6",
    tagline: "ChatGPT default since 9 Jul 2026 — Sol / Terra / Luna family, not one model",
    description:
      "Sol / Terra / Luna tiers. Intelligence Index 61 (Sol). Leads LiveBench math/reasoning and ARC-AGI-2. Canvas, agents, and the GPT ecosystem keep it the default consumer model.",
    license: "commercial",
    vendor: "OpenAI",
    website: "https://openai.com/chatgpt",
    categories: ["chat", "coding", "agents", "image"],
    techniques: ["moe", "test-time-compute", "tool-use", "rag"],
    features: ["Sol/Terra/Luna", "Canvas", "Agents", "Images 2.0", "Memory"],
    pricing: "ChatGPT Free–Pro + API",
    catalog_weight: 95,
    aliases: ["gpt-5.6", "gpt 5.6", "gpt5.6", "gpt-5.6 sol", "gpt-5.6 terra", "gpt-5.6 luna"],
    trend: 0.5,
    verified: "2026-07-09",
    spec: { contextK: 128, priceIn: 1.25, priceOut: 10, selfHost: false },
  },
  {
    id: "grok-4.6",
    kind: "model",
    name: "Grok 4.6",
    tagline: "Value frontier: Intelligence 61 at $2/$6 after 12 Aug post-training",
    description:
      "Not a new base model — extra agentic RL on Grok 4.5. Jumped 5 Intelligence points to 61, tying Sol. 500K context; prompts ≥200K rebill at $4/$12. Strong on long agentic jobs with fewer turns.",
    license: "commercial",
    vendor: "xAI",
    website: "https://x.ai",
    categories: ["chat", "coding", "agents"],
    techniques: ["rlhf", "test-time-compute", "tool-use", "multi-agent"],
    features: ["500K context", "Agentic RL", "Realtime X", "Imagine", "Fast value"],
    pricing: "$2 / $6 per 1M tokens",
    catalog_weight: 96,
    aliases: ["grok 4.6", "grok-4.6", "grok4.6"],
    trend: 3.4,
    verified: "2026-08-12",
    spec: { contextK: 500, priceIn: 2, priceOut: 6, selfHost: false },
  },
  {
    id: "gemini-3.1-pro",
    kind: "model",
    name: "Gemini 3.1 Pro",
    tagline: "Reasoning and multimodal flagship with million-token context",
    description:
      "Google’s paid flagship. Leads GPQA (94.3% in earlier 3.x line) and ties a human panel on ARC-AGI-1 at 98% for ~$0.52/task. Native Search, Docs, YouTube, and 1M-token context.",
    license: "commercial",
    vendor: "Google",
    website: "https://gemini.google.com",
    categories: ["chat", "research", "image", "video"],
    techniques: ["moe", "rag", "test-time-compute", "tool-use"],
    features: ["1M context", "Multimodal", "Search grounding", "Workspace"],
    pricing: "Google AI Pro/Ultra + API",
    catalog_weight: 91,
    aliases: ["gemini 3.1", "gemini-3.1-pro", "gemini 3"],
    trend: 0.7,
    verified: "2026-08-01",
    spec: { contextK: 1000, selfHost: false },
  },
  {
    id: "deepseek-r1",
    kind: "model",
    name: "DeepSeek-R1",
    tagline: "Historic open reasoner (Jan 2025) that popularized GRPO — not the current DeepSeek",
    description:
      "Open-weight reasoner. Distilled variants still run locally. Catalyzed the 2025–26 open-source surge. Superseded as DeepSeek’s frontier by V4-Pro (13 Aug 2026).",
    license: "open-source",
    vendor: "DeepSeek",
    website: "https://huggingface.co/deepseek-ai",
    github: "https://github.com/deepseek-ai/DeepSeek-R1",
    paper_url: "https://arxiv.org/abs/2501.12948",
    categories: ["open-models", "research", "coding", "local"],
    techniques: ["grpo", "test-time-compute", "distillation", "moe"],
    features: ["Open weights", "Reasoning traces", "Distilled sizes", "Cheap API"],
    pricing: "Open weights; API cents per M",
    catalog_weight: 78,
    aliases: ["deepseek-r1", "deepseek r1"],
    trend: 0.1,
    status: "historic",
    verified: "2025-01-20",
    spec: { selfHost: true },
  },
  {
    id: "deepseek-v4",
    kind: "model",
    name: "DeepSeek-V4",
    tagline: "Current DeepSeek frontier — V4-Pro-0813 shipped 13 Aug 2026",
    description:
      "Succeeds R1 as the lab’s live line. Open-weight and API. Use this id when ranking DeepSeek today; keep R1 on the map as the GRPO-era historic model.",
    license: "open-source",
    vendor: "DeepSeek",
    website: "https://www.deepseek.com",
    github: "https://github.com/deepseek-ai",
    categories: ["open-models", "coding", "chat", "research"],
    techniques: ["moe", "grpo", "test-time-compute", "distillation"],
    features: ["V4-Pro-0813", "Open weights", "Reasoning", "Cheap API"],
    pricing: "Open weights + API",
    catalog_weight: 90,
    aliases: ["deepseek-v4", "deepseek v4", "deepseek-v4-pro", "v4-pro-0813", "deepseek v4 pro"],
    trend: 2.2,
    verified: "2026-08-13",
    spec: { selfHost: true },
  },
  {
    id: "qwen-3",
    kind: "model",
    name: "Qwen3.8",
    tagline: "Alibaba’s current open line — 3.8-Max 2.4T MoE and 27B dense shipped 3 Aug 2026",
    description:
      "Canonical id remains qwen-3 so Atlas and Rankings join. Aliases cover Qwen3 / Qwen 3 / Qwen3.8. Apache-licensed options, strong multilingual and agent checkpoints.",
    license: "open-source",
    vendor: "Alibaba",
    website: "https://qwenlm.github.io",
    github: "https://github.com/QwenLM",
    categories: ["open-models", "chat", "coding", "local"],
    techniques: ["moe", "transformer", "quantization", "lora"],
    features: ["3.8-Max", "27B dense", "Apache options", "Multilingual"],
    pricing: "Open weights + DashScope API",
    catalog_weight: 89,
    aliases: ["qwen", "qwen3", "qwen 3", "qwen-3", "qwen3.8", "qwen 3.8", "qwen3.8-max", "qwen 3.8 max"],
    trend: 1.4,
    verified: "2026-08-03",
    spec: { contextK: 128, selfHost: true },
  },
  {
    id: "llama-4",
    kind: "model",
    name: "Llama 4",
    tagline: "Meta’s current open-weights generation — shipped Apr 2025, still the Western default",
    description:
      "Successor to the Llama 3.x line. Community license, broad tooling (llama.cpp, vLLM, Unsloth), and the default Western open base when teams cannot use Chinese-origin weights.",
    license: "open-source",
    vendor: "Meta",
    website: "https://www.llama.com",
    github: "https://github.com/meta-llama",
    categories: ["open-models", "local", "chat"],
    techniques: ["transformer", "gqa", "lora", "quantization"],
    features: ["Open weights", "Tooling everywhere", "Long context variants"],
    pricing: "Free weights (community license)",
    catalog_weight: 84,
    aliases: ["llama 4", "llama-4", "llama4"],
    trend: 0.3,
    verified: "2025-04-05",
    spec: { selfHost: true },
  },
  {
    id: "gpt-oss",
    kind: "model",
    name: "GPT-OSS",
    tagline: "OpenAI’s open-weight response to DeepSeek and Qwen adoption",
    description:
      "OpenAI open-weights collection on Hugging Face, aimed at commercially deployable Western alternatives to Chinese open models. Used as a fine-tune base more than a chat destination.",
    license: "open-source",
    vendor: "OpenAI",
    website: "https://huggingface.co/collections/openai/gpt-oss",
    categories: ["open-models", "local"],
    techniques: ["transformer", "distillation", "quantization"],
    features: ["Open weights", "Commercial-friendly", "HF collection"],
    pricing: "Free weights",
    catalog_weight: 74,
    aliases: ["gpt-oss", "gpt oss", "openai oss"],
    trend: 0.6,
    verified: "2026-08-21",
    spec: { selfHost: true },
  },
  {
    id: "gemma-3",
    kind: "model",
    name: "Gemma 3",
    tagline: "Google’s open-weight family for on-device and lightweight serving",
    description:
      "Permissive open models tuned for on-device, edge, and cheap server deployments. Strong documentation and Kaggle/HF distribution. Complementary to Gemini, not a replacement.",
    license: "open-source",
    vendor: "Google",
    website: "https://ai.google.dev/gemma",
    categories: ["open-models", "local"],
    techniques: ["transformer", "distillation", "quantization"],
    features: ["On-device", "Permissive license", "Multimodal variants"],
    pricing: "Free weights",
    catalog_weight: 72,
    aliases: ["gemma", "gemma 3", "gemma-3"],
    trend: 0.2,
    verified: "2026-08-21",
    spec: { selfHost: true },
  },

  // —— Chat / research tools ————————————————————————————————
  {
    id: "chatgpt",
    kind: "tool",
    name: "ChatGPT",
    tagline: "The default consumer assistant — largest surface area in AI",
    description:
      "GPT-5.6 default since 9 Jul 2026. Canvas, agents, memory, Images 2.0, Sora, and GPTs. Still the most versatile single product even when category specialists win on quality.",
    license: "commercial",
    vendor: "OpenAI",
    website: "https://chatgpt.com",
    categories: ["chat", "coding", "image", "video", "agents"],
    techniques: ["tool-use", "rag", "test-time-compute", "multi-agent"],
    features: ["Memory", "Canvas", "GPTs", "Agents", "Voice", "Images", "Sora"],
    pricing: "Free / Plus / Pro / Business",
    catalog_weight: 97,
    aliases: ["chatgpt", "chat gpt"],
    trend: 0.3,
  },
  {
    id: "claude",
    kind: "tool",
    name: "Claude",
    tagline: "Writing, analysis, and coding assistant — App Store #1 in early 2026",
    description:
      "Claude.ai with Opus 5 / Fable 5 / Sonnet. Artifacts, Projects, computer use, and Cowork (desktop agent). Preferred by people who write and ship, not just chat.",
    license: "commercial",
    vendor: "Anthropic",
    website: "https://claude.ai",
    categories: ["chat", "coding", "agents", "research"],
    techniques: ["constitutional-ai", "tool-use", "computer-use", "rag"],
    features: ["Projects", "Artifacts", "Cowork", "Computer use", "MCP"],
    pricing: "Free / Pro / Max / Team",
    catalog_weight: 96,
    aliases: ["claude.ai", "claude app"],
    trend: 1.4,
  },
  {
    id: "grok",
    kind: "tool",
    name: "Grok",
    tagline: "xAI assistant with realtime X firehose and Imagine media",
    description:
      "Consumer Grok on grok.com and X. Grok 4.6 backend, Imagine image/video, and live X context. Less censored house style; strong on current events and building.",
    license: "commercial",
    vendor: "xAI",
    website: "https://grok.com",
    categories: ["chat", "image", "video", "research"],
    techniques: ["tool-use", "rag", "test-time-compute"],
    features: ["Realtime X", "Imagine", "Grok Build", "Voice", "Projects"],
    pricing: "Free + X Premium/Premium+",
    catalog_weight: 93,
    aliases: ["grok.com", "grok app"],
    trend: 2.2,
  },
  {
    id: "gemini",
    kind: "tool",
    name: "Gemini",
    tagline: "Google-native assistant across Search, Workspace, and Android",
    description:
      "Gemini app plus Deep Research, Workspace side-panels, and Android. Best when the work already lives in Google; NotebookLM sits beside it for source-grounded research.",
    license: "commercial",
    vendor: "Google",
    website: "https://gemini.google.com",
    categories: ["chat", "research", "image"],
    techniques: ["rag", "tool-use", "test-time-compute"],
    features: ["Deep Research", "Workspace", "Gems", "Imagen", "Veo"],
    pricing: "Free / AI Pro / Ultra",
    catalog_weight: 90,
    aliases: ["gemini app", "google gemini"],
    trend: 0.5,
  },
  {
    id: "perplexity",
    kind: "tool",
    name: "Perplexity",
    tagline: "Cited research assistant — the lookup layer power users keep beside a generator",
    description:
      "Answer engine with mandatory citations, Spaces, and model choice. The usual pair with Claude or ChatGPT: one generates, Perplexity verifies.",
    license: "commercial",
    vendor: "Perplexity",
    website: "https://www.perplexity.ai",
    categories: ["search", "research", "chat"],
    techniques: ["rag", "tool-use"],
    features: ["Citations", "Spaces", "Focus modes", "Model picker", "Shopping"],
    pricing: "Free / Pro $20",
    catalog_weight: 87,
    aliases: ["perplexity"],
    trend: 0.4,
  },
  {
    id: "notebooklm",
    kind: "tool",
    name: "NotebookLM",
    tagline: "Source-grounded notebooks, audio overviews, and briefing docs",
    description:
      "Google’s research notebook that only answers from the sources you give it. Audio Overviews and study guides made it the default ‘read this corpus for me’ tool.",
    license: "commercial",
    vendor: "Google",
    website: "https://notebooklm.google.com",
    categories: ["research", "audio"],
    techniques: ["rag", "distillation"],
    features: ["Source grounding", "Audio Overviews", "Mind maps", "Briefings"],
    pricing: "Free + Google AI Pro features",
    catalog_weight: 80,
    aliases: ["notebooklm", "notebook lm"],
    trend: 0.6,
  },

  // —— Coding ———————————————————————————————————————————————
  {
    id: "cursor",
    kind: "tool",
    name: "Cursor",
    tagline: "Best all-round agentic IDE — multi-model, still the default starting point",
    description:
      "Anysphere’s fork of VS Code. Agent mode, background agents, repo index, and every frontier model including Grok 4.6. Share cooled 41%→26% on Ramp as ownership questions (SpaceX/Anysphere) landed, but still the most complete IDE.",
    license: "commercial",
    vendor: "Anysphere",
    website: "https://cursor.com",
    categories: ["coding", "agents"],
    techniques: ["rag", "tool-use", "multi-agent", "test-time-compute"],
    features: ["Agent", "Tab", "Background agents", "Multi-model", "Repo index", "Bugbot"],
    pricing: "Free / Pro / Ultra up to $200",
    catalog_weight: 94,
    aliases: ["cursor", "anysphere"],
    trend: -0.8,
  },
  {
    id: "claude-code",
    kind: "tool",
    name: "Claude Code",
    tagline: "Terminal-native agent with the strongest output-quality preference",
    description:
      "Anthropic’s CLI/desktop coding agent. Computer use and blind-review preference sit above Cursor on output quality. Pairs with Opus 5; plan-then-execute loop is the 2026 default for serious refactors.",
    license: "commercial",
    vendor: "Anthropic",
    website: "https://docs.anthropic.com/claude-code",
    github: "https://github.com/anthropics/claude-code",
    categories: ["coding", "agents"],
    techniques: ["computer-use", "tool-use", "multi-agent", "test-time-compute"],
    features: ["CLI agent", "Computer use", "Plan mode", "MCP", "Git-native"],
    pricing: "Claude Pro/Max usage",
    catalog_weight: 93,
    aliases: ["claude code", "claude-code"],
    trend: 2.1,
  },
  {
    id: "grok-build",
    kind: "tool",
    name: "Grok Build",
    tagline: "xAI’s in-browser app builder with live preview and Grok 4.6",
    description:
      "Agentic product builder inside Grok. Ships full-stack previews, uses Grok 4.6 day-one, and sits beside Cursor for people who want to go from prompt to running product without an IDE.",
    license: "commercial",
    vendor: "xAI",
    website: "https://grok.com",
    categories: ["coding", "agents"],
    techniques: ["tool-use", "multi-agent", "test-time-compute"],
    features: ["Live preview", "Full-stack", "Grok 4.6", "Brand/UI skills"],
    pricing: "Included with Grok / SuperGrok",
    catalog_weight: 86,
    aliases: ["grok build", "grok-build"],
    trend: 2.6,
  },
  {
    id: "github-copilot",
    kind: "tool",
    name: "GitHub Copilot",
    tagline: "Best-value coding assistant inside the GitHub gravity well",
    description:
      "Completions, Chat, and agent mode across VS Code, JetBrains, and github.com. Enterprise SSO and Copilot Workspace keep it the default in companies that already buy GitHub.",
    license: "commercial",
    vendor: "GitHub / Microsoft",
    website: "https://github.com/features/copilot",
    categories: ["coding", "agents"],
    techniques: ["rag", "tool-use"],
    features: ["Completions", "Chat", "Agent", "Workspace", "Enterprise"],
    pricing: "Free–$39/mo + Enterprise",
    catalog_weight: 85,
    aliases: ["github copilot", "copilot"],
    trend: 0.1,
  },
  {
    id: "codex",
    kind: "tool",
    name: "OpenAI Codex",
    tagline: "OpenAI’s software-engineering agent, sibling to ChatGPT",
    description:
      "Cloud and CLI coding agent on GPT-5.6. Strong on repo-scale tasks and GitHub integration; the OpenAI-native alternative to Claude Code and Cursor agents.",
    license: "commercial",
    vendor: "OpenAI",
    website: "https://openai.com/codex",
    categories: ["coding", "agents"],
    techniques: ["tool-use", "multi-agent", "test-time-compute"],
    features: ["Cloud agent", "CLI", "PR workflows", "Sandbox"],
    pricing: "ChatGPT Plus/Pro / API",
    catalog_weight: 84,
    aliases: ["codex", "openai codex"],
    trend: 0.9,
  },
  {
    id: "windsurf",
    kind: "tool",
    name: "Windsurf",
    tagline: "Cascade agent IDE — Claude-powered alternative to Cursor",
    description:
      "Codeium’s Windsurf editor. Cascade flows and Claude-default models made it the main Cursor alternative before the 2026 consolidation wave.",
    license: "commercial",
    vendor: "Windsurf",
    website: "https://windsurf.com",
    categories: ["coding", "agents"],
    techniques: ["rag", "tool-use"],
    features: ["Cascade", "Flows", "Multi-model", "Fast tab"],
    pricing: "Free / Pro",
    catalog_weight: 76,
    aliases: ["windsurf", "codeium", "cascade"],
    trend: -0.4,
  },
  {
    id: "zed",
    kind: "tool",
    name: "Zed",
    tagline: "Rust-native editor with collaborative AI, built for speed",
    description:
      "GPU-accelerated editor from the Atom team. Agent panel plus multiplayer editing; the choice when Cursor feels heavy and you still want inline AI.",
    license: "open-source",
    vendor: "Zed Industries",
    website: "https://zed.dev",
    github: "https://github.com/zed-industries/zed",
    categories: ["coding"],
    techniques: ["tool-use"],
    features: ["Native speed", "Collaboration", "Agent panel", "Open source"],
    pricing: "Free; usage-based AI",
    catalog_weight: 74,
    aliases: ["zed", "zed.dev"],
    trend: 0.5,
  },
  {
    id: "aider",
    kind: "tool",
    name: "Aider",
    tagline: "Open-source pair programmer that commits against a local repo",
    description:
      "CLI that maps a repo, proposes diffs, and commits. Model-agnostic (OpenRouter, local, frontier). The frugal, scriptable coding agent.",
    license: "open-source",
    vendor: "Aider",
    website: "https://aider.chat",
    github: "https://github.com/Aider-AI/aider",
    categories: ["coding", "local"],
    techniques: ["tool-use", "rag"],
    features: ["Git-native", "Any model", "Voice", "Watch mode"],
    pricing: "Free (bring a model)",
    catalog_weight: 73,
    aliases: ["aider"],
    trend: 0.3,
  },
  {
    id: "cline",
    kind: "tool",
    name: "Cline",
    tagline: "Autonomous VS Code agent with MCP and plan/act modes",
    description:
      "Open-source VS Code agent (and cousins Roo/Continue). Plan/act, browser, and MCP tools. Default for people who want Cursor-class agents on their own keys.",
    license: "open-source",
    vendor: "Cline",
    website: "https://cline.bot",
    github: "https://github.com/cline/cline",
    categories: ["coding", "agents"],
    techniques: ["tool-use", "computer-use", "multi-agent"],
    features: ["Plan/Act", "MCP", "Browser", "Bring your keys"],
    pricing: "Free (bring a model)",
    catalog_weight: 75,
    aliases: ["cline", "roo", "roo code"],
    trend: 0.8,
  },
  {
    id: "v0",
    kind: "tool",
    name: "v0",
    tagline: "Vercel’s UI generator that emits shadcn/React ready to ship",
    description:
      "Prompt-to-interface for Next/React. Tightest path from mock to deployed Vercel app. 2026 versions added fuller product generation, still strongest on UI.",
    license: "commercial",
    vendor: "Vercel",
    website: "https://v0.dev",
    categories: ["coding", "image"],
    techniques: ["tool-use"],
    features: ["shadcn output", "Vercel deploy", "Iterate in chat"],
    pricing: "Free / Premium",
    catalog_weight: 77,
    aliases: ["v0", "v0.dev", "vercel v0"],
    trend: 0.4,
  },
  {
    id: "lovable",
    kind: "tool",
    name: "Lovable",
    tagline: "Prompt-to-full-stack web app for builders who skip the IDE",
    description:
      "Chat-native product builder. Competes with Bolt, v0, and Grok Build for ‘describe a SaaS, get a running app’. Strong on CRUD and auth starters.",
    license: "commercial",
    vendor: "Lovable",
    website: "https://lovable.dev",
    categories: ["coding", "agents"],
    techniques: ["tool-use", "multi-agent"],
    features: ["Full-stack", "Supabase", "Visual edit", "GitHub sync"],
    pricing: "Free / paid credits",
    catalog_weight: 72,
    aliases: ["lovable", "gpt-engineer"],
    trend: 0.3,
  },
  {
    id: "bolt",
    kind: "tool",
    name: "Bolt.new",
    tagline: "StackBlitz-in-browser agent that runs the app while it writes it",
    description:
      "WebContainers let Bolt install, run, and fix the app in the browser. Fastest path for JS prototypes; weaker the moment you leave the Node web ecosystem.",
    license: "commercial",
    vendor: "StackBlitz",
    website: "https://bolt.new",
    categories: ["coding"],
    techniques: ["tool-use"],
    features: ["In-browser runtime", "One-click deploy", "Chat edits"],
    pricing: "Free / token plans",
    catalog_weight: 70,
    aliases: ["bolt", "bolt.new", "stackblitz"],
    trend: 0.1,
  },
  {
    id: "replit-agent",
    kind: "tool",
    name: "Replit Agent",
    tagline: "Cloud workspace that builds, runs, and hosts in one tab",
    description:
      "Agent plus always-on Repl. Best when the user is not a developer and needs hosting included. The education and hobby default.",
    license: "commercial",
    vendor: "Replit",
    website: "https://replit.com",
    categories: ["coding", "agents"],
    techniques: ["tool-use"],
    features: ["Hosted runtime", "Agent", "Deploy", "Multiplayer"],
    pricing: "Free / Core / Pro",
    catalog_weight: 71,
    aliases: ["replit", "replit agent"],
    trend: 0.2,
  },

  // —— Image / video / audio ————————————————————————————————
  {
    id: "midjourney",
    kind: "tool",
    name: "Midjourney",
    tagline: "Still the taste leader for still images",
    description:
      "Discord + web image model with the most recognizable aesthetic. Moodboards, personalization, and style references keep it the art-direction default in 2026.",
    license: "commercial",
    vendor: "Midjourney",
    website: "https://www.midjourney.com",
    categories: ["image"],
    techniques: ["diffusion"],
    features: ["Moodboards", "Style ref", "Editor", "Video experiments"],
    pricing: "Standard–Mega subscriptions",
    catalog_weight: 88,
    aliases: ["midjourney", "mj"],
    trend: 0.2,
  },
  {
    id: "flux",
    kind: "model",
    name: "FLUX",
    tagline: "Open (and commercial) photoreal image family from Black Forest Labs",
    description:
      "The open-side default that displaced SD3 in most ComfyUI graphs. FLUX.1 [dev]/[schnell]/pro cover local and API. Text rendering still trails Ideogram/ChatGPT Images.",
    license: "mixed",
    vendor: "Black Forest Labs",
    website: "https://blackforestlabs.ai",
    github: "https://github.com/black-forest-labs/flux",
    categories: ["image", "open-models"],
    techniques: ["diffusion", "quantization"],
    features: ["Open weights", "ComfyUI native", "API pro", "Schnell fast"],
    pricing: "Open dev/schnell; paid pro",
    catalog_weight: 85,
    aliases: ["flux", "flux.1", "black forest"],
    trend: 0.5,
    verified: "2026-08-21",
    spec: { selfHost: true },
  },
  {
    id: "chatgpt-images",
    kind: "tool",
    name: "ChatGPT Images 2.0",
    tagline: "Arena image-board leader — best in-chat editing loop",
    description:
      "OpenAI’s in-product image stack. Leads public image arenas in 2026 and wins on instruction following plus in-thread edits. Not a batch art-direction tool like Midjourney.",
    license: "commercial",
    vendor: "OpenAI",
    website: "https://chatgpt.com",
    categories: ["image"],
    techniques: ["diffusion", "tool-use"],
    features: ["In-chat edit", "Instruction following", "Referenced images"],
    pricing: "Included with ChatGPT paid",
    catalog_weight: 86,
    aliases: ["dall-e", "dalle", "chatgpt images", "images 2.0"],
    trend: 1.0,
  },
  {
    id: "ideogram",
    kind: "tool",
    name: "Ideogram",
    tagline: "Best-in-class text-in-image and poster layouts",
    description:
      "Specialist image model for logos, posters, and readable lettering. The tool designers actually open when the brief has words in the frame.",
    license: "commercial",
    vendor: "Ideogram",
    website: "https://ideogram.ai",
    categories: ["image"],
    techniques: ["diffusion"],
    features: ["Text rendering", "Magic Fill", "Batch", "Typography"],
    pricing: "Free / Plus / Pro",
    catalog_weight: 78,
    aliases: ["ideogram"],
    trend: 0.3,
  },
  {
    id: "comfyui",
    kind: "tool",
    name: "ComfyUI",
    tagline: "Node-graph image/video engine — the professional open pipeline",
    description:
      "The DAW of generative visuals. FLUX, video, ControlNet, IP-Adapter, and custom nodes. Steeper than Automatic1111; unbeatable once a pipeline exists.",
    license: "open-source",
    vendor: "Comfy Org",
    website: "https://github.com/comfyanonymous/ComfyUI",
    github: "https://github.com/comfyanonymous/ComfyUI",
    categories: ["image", "video", "local"],
    techniques: ["diffusion", "lora"],
    features: ["Node graph", "Custom nodes", "Video", "API mode"],
    pricing: "Free; Comfy Cloud paid",
    catalog_weight: 84,
    aliases: ["comfyui", "comfy ui", "comfy"],
    trend: 0.6,
  },
  {
    id: "runway",
    kind: "tool",
    name: "Runway",
    tagline: "Gen-3/4 video with the most mature editing suite",
    description:
      "Act-One, Director Mode, and in-app editing keep Runway the production video tool even when Kling or Veo win a raw-fidelity bake-off.",
    license: "commercial",
    vendor: "Runway",
    website: "https://runwayml.com",
    categories: ["video"],
    techniques: ["diffusion"],
    features: ["Gen-3/4", "Act-One", "Inpainting", "Editor"],
    pricing: "Credit plans",
    catalog_weight: 82,
    aliases: ["runway", "runwayml"],
    trend: 0.2,
  },
  {
    id: "kling",
    kind: "tool",
    name: "Kling",
    tagline: "Kuaishou’s cinematic video model — motion quality leader in many 2026 tests",
    description:
      "High-fidelity text/image-to-video from Kuaishou. Competes with Veo and Runway on camera motion and duration. Access via Kling web and aggregators.",
    license: "commercial",
    vendor: "Kuaishou",
    website: "https://klingai.com",
    categories: ["video"],
    techniques: ["diffusion"],
    features: ["Longer clips", "Camera control", "Image-to-video"],
    pricing: "Credit plans",
    catalog_weight: 80,
    aliases: ["kling", "kling ai"],
    trend: 0.7,
  },
  {
    id: "veo",
    kind: "model",
    name: "Veo",
    tagline: "Google’s video family — Omni Flash leads several public video boards",
    description:
      "Veo inside Gemini/YouTube Shorts pipelines. Strong native audio+video in later Omni Flash revisions. Best if you already live in Google.",
    license: "commercial",
    vendor: "Google",
    website: "https://deepmind.google/models/veo",
    categories: ["video"],
    techniques: ["diffusion"],
    features: ["Native audio", "DeepMind stack", "Gemini integration"],
    pricing: "Google AI Pro/Ultra",
    catalog_weight: 81,
    aliases: ["veo", "veo 3", "omni flash"],
    trend: 0.8,
    verified: "2026-08-21",
    spec: { selfHost: false },
  },
  {
    id: "sora",
    kind: "model",
    name: "Sora",
    tagline: "OpenAI video inside ChatGPT — strongest story-and-shot coherence",
    description:
      "Cameos, remix, and ChatGPT-native iteration. Not always the raw-fidelity winner versus Kling/Veo, but the most usable narrative loop.",
    license: "commercial",
    vendor: "OpenAI",
    website: "https://openai.com/sora",
    categories: ["video"],
    techniques: ["diffusion"],
    features: ["Cameos", "Remix", "ChatGPT loop", "Storyboard"],
    pricing: "ChatGPT Plus/Pro",
    catalog_weight: 83,
    aliases: ["sora", "sora 2"],
    trend: 0.4,
    verified: "2026-08-21",
    spec: { selfHost: false },
  },
  {
    id: "elevenlabs",
    kind: "tool",
    name: "ElevenLabs",
    tagline: "Voice cloning, TTS, and conversational agents",
    description:
      "The production TTS default. Instant/professional clones, Dubbing Studio, and a voice-agent platform. Also the API behind many other products’ speech.",
    license: "commercial",
    vendor: "ElevenLabs",
    website: "https://elevenlabs.io",
    categories: ["audio", "agents"],
    techniques: ["diffusion", "distillation"],
    features: ["TTS", "Cloning", "Dubbing", "Voice agents"],
    pricing: "Free / Creator / Pro",
    catalog_weight: 82,
    aliases: ["elevenlabs", "eleven labs"],
    trend: 0.4,
  },
  {
    id: "suno",
    kind: "tool",
    name: "Suno",
    tagline: "Full-song generation from a prompt — the consumer music default",
    description:
      "End-to-end songs with vocals. v4+ improved stems and upload-to-extend. Competes with Udio; Suno still wins on ‘hit the generate button’ feel.",
    license: "commercial",
    vendor: "Suno",
    website: "https://suno.com",
    categories: ["audio"],
    techniques: ["diffusion", "transformer"],
    features: ["Full songs", "Stems", "Extend", "Personas"],
    pricing: "Free / Pro / Premier",
    catalog_weight: 79,
    aliases: ["suno"],
    trend: 0.3,
  },

  // —— Local / infra ————————————————————————————————————————
  {
    id: "ollama",
    kind: "tool",
    name: "Ollama",
    tagline: "One-command local models — the Homebrew of LLM runtimes",
    description:
      "Pull, run, and serve GGUF models with a dead-simple CLI and HTTP API. Pairs with Open WebUI. The on-ramp for local Llama/Qwen/DeepSeek/Gemma.",
    license: "open-source",
    vendor: "Ollama",
    website: "https://ollama.com",
    github: "https://github.com/ollama/ollama",
    categories: ["local", "infra"],
    techniques: ["quantization"],
    features: ["CLI", "Model library", "OpenAI-compatible API", "Modelfiles"],
    pricing: "Free",
    catalog_weight: 88,
    aliases: ["ollama"],
    trend: 0.5,
  },
  {
    id: "llama-cpp",
    kind: "tool",
    name: "llama.cpp",
    tagline: "The C/C++ runtime every local stack eventually touches",
    description:
      "Georgi Gerganov’s inference engine. GGUF, Apple Silicon, CUDA, Vulkan. Backend for Ollama, LM Studio, and countless bindings.",
    license: "open-source",
    vendor: "ggerganov",
    website: "https://github.com/ggml-org/llama.cpp",
    github: "https://github.com/ggml-org/llama.cpp",
    categories: ["local", "infra"],
    techniques: ["quantization", "speculative-decoding"],
    features: ["GGUF", "Metal/CUDA/Vulkan", "Server", "Bindings"],
    pricing: "Free",
    catalog_weight: 90,
    aliases: ["llama.cpp", "llamacpp", "gguf", "ggml"],
    trend: 0.4,
  },
  {
    id: "vllm",
    kind: "tool",
    name: "vLLM",
    tagline: "PagedAttention serving engine — production open inference default",
    description:
      "High-throughput OpenAI-compatible server. PagedAttention, continuous batching, prefix caching, LoRA, and multimodal. What you run when Ollama is no longer enough.",
    license: "open-source",
    vendor: "vLLM",
    website: "https://github.com/vllm-project/vllm",
    github: "https://github.com/vllm-project/vllm",
    categories: ["infra", "local"],
    techniques: ["flash-attention", "prefix-caching", "speculative-decoding", "quantization"],
    features: ["PagedAttention", "OpenAI API", "LoRA", "Prefix cache"],
    pricing: "Free",
    catalog_weight: 89,
    aliases: ["vllm", "v llm"],
    trend: 0.6,
  },
  {
    id: "lm-studio",
    kind: "tool",
    name: "LM Studio",
    tagline: "Desktop GUI for local models, MCP, and a built-in chat/server",
    description:
      "The non-CLI local stack. Hugging Face search, GGUF/MLX, OpenAI-compatible server, and MCP. Default recommendation for ‘I have a Mac and I want local ChatGPT’.",
    license: "commercial",
    vendor: "LM Studio",
    website: "https://lmstudio.ai",
    categories: ["local", "chat"],
    techniques: ["quantization", "tool-use"],
    features: ["GUI", "MCP", "Server", "MLX/GGUF"],
    pricing: "Free for personal use",
    catalog_weight: 80,
    aliases: ["lm studio", "lmstudio"],
    trend: 0.4,
  },
  {
    id: "open-webui",
    kind: "tool",
    name: "Open WebUI",
    tagline: "Self-hosted ChatGPT-style frontend for Ollama, OpenAI, and local stacks",
    description:
      "The most popular open chat UI. RAG, pipelines, multi-user, and tools. Sits in front of Ollama/vLLM for teams that will not pay ChatGPT.",
    license: "open-source",
    vendor: "Open WebUI",
    website: "https://openwebui.com",
    github: "https://github.com/open-webui/open-webui",
    categories: ["local", "chat"],
    techniques: ["rag", "tool-use"],
    features: ["RAG", "Multi-user", "Pipelines", "Tools"],
    pricing: "Free",
    catalog_weight: 81,
    aliases: ["open webui", "open-webui", "owui"],
    trend: 0.5,
  },
  {
    id: "openrouter",
    kind: "tool",
    name: "OpenRouter",
    tagline: "One API key for every model, with fallbacks and price routing",
    description:
      "The multi-model switchboard. Rankings, provider uptime, and a single OpenAI-shaped API. How most indie agents actually call Grok, Claude, Gemini, and DeepSeek.",
    license: "commercial",
    vendor: "OpenRouter",
    website: "https://openrouter.ai",
    categories: ["infra"],
    techniques: ["tool-use"],
    features: ["Unified API", "Fallbacks", "Rankings", "BYOK"],
    pricing: "Pass-through + small fee",
    catalog_weight: 87,
    aliases: ["openrouter", "open router"],
    trend: 0.7,
  },
  {
    id: "groq",
    kind: "tool",
    name: "Groq",
    tagline: "LPU inference — fastest tokens for open models",
    description:
      "Hardware-specialized inference. When an app needs Llama/Qwen/DeepSeek at conversational latency, Groq is still the speed king among public APIs.",
    license: "commercial",
    vendor: "Groq",
    website: "https://groq.com",
    categories: ["infra"],
    techniques: ["quantization"],
    features: ["LPU speed", "Open model catalog", "OpenAI-compatible"],
    pricing: "Generous free + usage",
    catalog_weight: 79,
    aliases: ["groq", "groqcloud"],
    trend: 0.2,
  },
  {
    id: "together",
    kind: "tool",
    name: "Together AI",
    tagline: "Train and serve open models without standing up GPU ops",
    description:
      "Inference + fine-tunes for Llama, Qwen, FLUX, and others. The cloud counterpart to vLLM when you do not want to own H100s.",
    license: "commercial",
    vendor: "Together AI",
    website: "https://www.together.ai",
    categories: ["infra", "open-models"],
    techniques: ["lora", "flash-attention"],
    features: ["Inference", "Fine-tunes", "GPU clusters", "Image models"],
    pricing: "Usage-based",
    catalog_weight: 76,
    aliases: ["together", "together.ai"],
    trend: 0.2,
  },

  // —— Frameworks / data / eval ————————————————————————————
  {
    id: "langchain",
    kind: "tool",
    name: "LangChain",
    tagline: "The default orchestration SDK — LCEL, LangGraph, and LangSmith",
    description:
      "Python/JS framework plus LangGraph for cyclic agents and LangSmith for traces. Still the ecosystem with the most tutorials, for better and worse.",
    license: "open-source",
    vendor: "LangChain",
    website: "https://www.langchain.com",
    github: "https://github.com/langchain-ai/langchain",
    categories: ["agents", "infra"],
    techniques: ["rag", "multi-agent", "tool-use", "react-pattern"],
    features: ["LCEL", "LangGraph", "LangSmith", "Integrations"],
    pricing: "Open source; Smith paid",
    catalog_weight: 86,
    aliases: ["langchain", "langgraph", "langsmith"],
    trend: 0.3,
  },
  {
    id: "langgraph",
    kind: "tool",
    name: "LangGraph",
    tagline: "Durable, cyclic agent graphs with checkpointing",
    description:
      "The serious subset of LangChain. State machines, human-in-the-loop, and durable execution. What production agent teams actually keep after deleting the rest.",
    license: "open-source",
    vendor: "LangChain",
    website: "https://www.langchain.com/langgraph",
    github: "https://github.com/langchain-ai/langgraph",
    categories: ["agents"],
    techniques: ["multi-agent", "tool-use", "react-pattern"],
    features: ["Checkpoints", "HITL", "Cycles", "Studio"],
    pricing: "Open source; Cloud paid",
    catalog_weight: 84,
    aliases: ["langgraph"],
    trend: 0.8,
  },
  {
    id: "llamaindex",
    kind: "tool",
    name: "LlamaIndex",
    tagline: "Data framework for RAG — parsers, indexes, and query engines",
    description:
      "Ingestion + retrieval specialist. Often paired with LangGraph (graph for control, LlamaIndex for knowledge). LlamaParse is the PDF workhorse.",
    license: "open-source",
    vendor: "LlamaIndex",
    website: "https://www.llamaindex.ai",
    github: "https://github.com/run-llama/llama_index",
    categories: ["data", "infra"],
    techniques: ["rag", "graphrag", "agentic-rag"],
    features: ["LlamaParse", "Indexes", "Agents", "Cloud"],
    pricing: "Open source; Cloud paid",
    catalog_weight: 82,
    aliases: ["llamaindex", "llama index", "llama-index"],
    trend: 0.3,
  },
  {
    id: "dspy",
    kind: "tool",
    name: "DSPy",
    tagline: "Compile prompts and weights from a metric, not a vibe",
    description:
      "Stanford’s programming model for LM pipelines. Signatures, teleprompters, and optimizers replace hand-tuned prompts. The grown-up alternative to prompt spaghetti.",
    license: "open-source",
    vendor: "Stanford NLP",
    website: "https://dspy.ai",
    github: "https://github.com/stanfordnlp/dspy",
    paper_url: "https://arxiv.org/abs/2310.03714",
    categories: ["eval", "infra"],
    techniques: ["distillation", "rag"],
    features: ["Signatures", "Optimizers", "Assertions", "MIPRO"],
    pricing: "Free",
    catalog_weight: 77,
    aliases: ["dspy"],
    trend: 0.5,
  },
  {
    id: "crewai",
    kind: "tool",
    name: "CrewAI",
    tagline: "Role-playing multi-agent crews with a low-code studio",
    description:
      "Opinionated multi-agent: agents, tasks, crews. Faster to a demo than LangGraph; less durable for long-running systems. Huge tutorial gravity.",
    license: "open-source",
    vendor: "CrewAI",
    website: "https://www.crewai.com",
    github: "https://github.com/crewAIInc/crewAI",
    categories: ["agents"],
    techniques: ["multi-agent", "tool-use"],
    features: ["Roles", "Flows", "Studio", "Tools"],
    pricing: "Open source; Cloud paid",
    catalog_weight: 74,
    aliases: ["crewai", "crew ai"],
    trend: 0.2,
  },
  {
    id: "n8n",
    kind: "tool",
    name: "n8n",
    tagline: "Open-source workflow automation that now speaks MCP and agents",
    description:
      "Self-hostable Zapier. 2025–26 added native AI nodes and MCP. The frugal ops layer for gluing models to Slack, sheets, and CRMs.",
    license: "open-source",
    vendor: "n8n",
    website: "https://n8n.io",
    github: "https://github.com/n8n-io/n8n",
    categories: ["automation", "agents"],
    techniques: ["tool-use", "multi-agent"],
    features: ["Self-host", "AI nodes", "MCP", "400+ integrations"],
    pricing: "Free self-host / Cloud",
    catalog_weight: 80,
    aliases: ["n8n"],
    trend: 0.9,
  },
  {
    id: "pinecone",
    kind: "tool",
    name: "Pinecone",
    tagline: "Managed vector database — still the RAG default in enterprises",
    description:
      "Serverless vectors, namespaces, and sparse-dense hybrid. Competes with Qdrant, Weaviate, pgvector. Wins on ops, not on price.",
    license: "commercial",
    vendor: "Pinecone",
    website: "https://www.pinecone.io",
    categories: ["data"],
    techniques: ["rag"],
    features: ["Serverless", "Hybrid search", "Namespaces", "Assistants"],
    pricing: "Free / Standard / Enterprise",
    catalog_weight: 75,
    aliases: ["pinecone"],
    trend: 0.0,
  },
  {
    id: "qdrant",
    kind: "tool",
    name: "Qdrant",
    tagline: "Open-source vector DB with strong filters and a cloud option",
    description:
      "Rust vector search. Payload filters, hybrid, and cheap self-host. The usual recommendation when Pinecone feels expensive and pgvector feels early.",
    license: "open-source",
    vendor: "Qdrant",
    website: "https://qdrant.tech",
    github: "https://github.com/qdrant/qdrant",
    categories: ["data"],
    techniques: ["rag"],
    features: ["Filters", "Hybrid", "Cloud + OSS", "Quantization"],
    pricing: "Free OSS / Cloud",
    catalog_weight: 76,
    aliases: ["qdrant"],
    trend: 0.4,
  },
  {
    id: "langsmith",
    kind: "tool",
    name: "LangSmith",
    tagline: "Traces, evals, and prompt hub for LangChain and anything else",
    description:
      "Observability + evaluation. Datasets, online evals, and playground. Pair with Promptfoo when you want CI-native assertions.",
    license: "commercial",
    vendor: "LangChain",
    website: "https://www.langchain.com/langsmith",
    categories: ["eval"],
    techniques: ["rag"],
    features: ["Tracing", "Evals", "Prompts", "Annotation"],
    pricing: "Free tier / Plus",
    catalog_weight: 78,
    aliases: ["langsmith"],
    trend: 0.3,
  },
  {
    id: "promptfoo",
    kind: "tool",
    name: "Promptfoo",
    tagline: "Open-source evals and red-team as CI",
    description:
      "YAML evals, assertions, red-team plugins, and a local viewer. The frugal eval harness — git-native, no vendor lock-in.",
    license: "open-source",
    vendor: "Promptfoo",
    website: "https://www.promptfoo.dev",
    github: "https://github.com/promptfoo/promptfoo",
    categories: ["eval"],
    techniques: ["rag"],
    features: ["CI evals", "Red team", "Local viewer", "Providers"],
    pricing: "Free OSS / Enterprise",
    catalog_weight: 74,
    aliases: ["promptfoo", "prompt foo"],
    trend: 0.5,
  },
  {
    id: "unsloth",
    kind: "tool",
    name: "Unsloth",
    tagline: "Fast, low-VRAM fine-tunes for Llama, Qwen, and friends",
    description:
      "Custom kernels that cut VRAM and wall-time for LoRA/QLoRA. The practical 2026 path to a domain model on a single consumer GPU.",
    license: "open-source",
    vendor: "Unsloth",
    website: "https://unsloth.ai",
    github: "https://github.com/unslothai/unsloth",
    categories: ["infra", "open-models"],
    techniques: ["lora", "quantization"],
    features: ["2x faster", "Low VRAM", "Colab notebooks", "GRPO"],
    pricing: "Free",
    catalog_weight: 77,
    aliases: ["unsloth"],
    trend: 0.6,
  },

  // —— Protocols ————————————————————————————————————————————
  {
    id: "mcp",
    kind: "protocol",
    name: "Model Context Protocol",
    tagline: "Open standard for tools, resources, and prompts — the USB-C of agents",
    description:
      "Anthropic-origin open protocol now in Claude, Cursor, Cline, LM Studio, OpenAI, and n8n. One server, many clients. The integration layer of 2026.",
    license: "open-source",
    vendor: "Anthropic + contributors",
    website: "https://modelcontextprotocol.io",
    github: "https://github.com/modelcontextprotocol",
    categories: ["agents", "infra"],
    techniques: ["tool-use"],
    features: ["Tools", "Resources", "Prompts", "Servers everywhere"],
    pricing: "Free standard",
    catalog_weight: 92,
    aliases: ["mcp", "model context protocol"],
    trend: 1.7,
  },

  // —— Techniques ———————————————————————————————————————————
  {
    id: "transformer",
    kind: "technique",
    name: "Transformer",
    tagline: "Attention-based sequence model — the substrate of modern AI",
    description:
      "Vaswani et al. 2017. Self-attention replaced recurrence. Every frontier LM, most diffusion backbones, and the paper every other paper still cites.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/1706.03762",
    paper_url: "https://arxiv.org/abs/1706.03762",
    categories: ["research"],
    techniques: [],
    features: ["Self-attention", "Positional encodings", "Scaled dot-product"],
    pricing: "—",
    catalog_weight: 99,
    aliases: ["transformer", "self-attention", "vaswani"],
    trend: 0.0,
  },
  {
    id: "moe",
    kind: "technique",
    name: "Mixture of Experts",
    tagline: "Sparse routing so only a slice of parameters fire per token",
    description:
      "The scaling trick behind Mixtral, DeepSeek-V3, and several frontier closed models. Train huge, serve cheap(er). Load-balancing and routing quality are the unsolved bits.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/2401.04088",
    paper_url: "https://arxiv.org/abs/2401.04088",
    categories: ["research", "infra"],
    techniques: [],
    features: ["Sparse activation", "Router", "Shared experts"],
    pricing: "—",
    catalog_weight: 88,
    aliases: ["moe", "mixture of experts", "mixtral"],
    trend: 0.4,
  },
  {
    id: "rag",
    kind: "technique",
    name: "RAG",
    tagline: "Retrieve then generate — still how most products know private data",
    description:
      "Lewis et al. Embed, retrieve, stuff context, generate. 2026 production RAG is hybrid search + rerank + citations + evals, not a single vector call.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/2005.11401",
    paper_url: "https://arxiv.org/abs/2005.11401",
    categories: ["data", "research"],
    techniques: [],
    features: ["Embeddings", "Hybrid search", "Rerank", "Citations"],
    pricing: "—",
    catalog_weight: 90,
    aliases: ["rag", "retrieval augmented", "retrieval-augmented"],
    trend: 0.2,
  },
  {
    id: "graphrag",
    kind: "technique",
    name: "GraphRAG",
    tagline: "Knowledge graphs over corpora for multi-hop questions",
    description:
      "Microsoft GraphRAG and cousins. Extract entities/relations, community-summarize, then retrieve along the graph. Worth it when the question is relational, expensive when it is not.",
    license: "open-source",
    vendor: "Microsoft Research",
    website: "https://github.com/microsoft/graphrag",
    github: "https://github.com/microsoft/graphrag",
    paper_url: "https://arxiv.org/abs/2404.16130",
    categories: ["data", "research"],
    techniques: ["rag"],
    features: ["Entity graphs", "Community summaries", "Multi-hop"],
    pricing: "Free (compute-heavy)",
    catalog_weight: 72,
    aliases: ["graphrag", "graph rag"],
    trend: 0.1,
  },
  {
    id: "agentic-rag",
    kind: "technique",
    name: "Agentic RAG",
    tagline: "Let the model decide what to retrieve, rewrite, and verify",
    description:
      "RAG with a loop: query rewrite, tool choice, critique, and re-retrieve. Default 2026 pattern in LangGraph and production support bots. Costs more; fails less silently.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/2501.09136",
    categories: ["agents", "data"],
    techniques: ["rag", "tool-use", "react-pattern"],
    features: ["Query rewrite", "Self-critique", "Multi-step retrieve"],
    pricing: "—",
    catalog_weight: 83,
    aliases: ["agentic rag", "agentic-rag"],
    trend: 0.9,
  },
  {
    id: "lora",
    kind: "technique",
    name: "LoRA / QLoRA",
    tagline: "Low-rank adapters so fine-tunes fit on one GPU",
    description:
      "Hu et al. LoRA plus Dettmers QLoRA. The practical fine-tune. Unsloth, Axolotl, and TRL all assume it. Full fine-tunes are for labs; adapters are for everyone else.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/2106.09685",
    paper_url: "https://arxiv.org/abs/2106.09685",
    categories: ["infra", "open-models"],
    techniques: ["quantization"],
    features: ["Low-rank adapters", "4-bit QLoRA", "Composable"],
    pricing: "—",
    catalog_weight: 85,
    aliases: ["lora", "qlora", "low-rank"],
    trend: 0.3,
  },
  {
    id: "rlhf",
    kind: "technique",
    name: "RLHF",
    tagline: "Reinforcement learning from human (or AI) preferences",
    description:
      "InstructGPT lineage. PPO on a reward model. Still used, but DPO/GRPO/RFT variants ate a lot of the complexity. The conceptual parent of every aligned chat model.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/2203.02155",
    paper_url: "https://arxiv.org/abs/2203.02155",
    categories: ["research"],
    techniques: [],
    features: ["Reward model", "PPO", "Preference data"],
    pricing: "—",
    catalog_weight: 86,
    aliases: ["rlhf", "reinforcement learning from human"],
    trend: 0.1,
  },
  {
    id: "dpo",
    kind: "technique",
    name: "DPO",
    tagline: "Direct preference optimization — RLHF without a reward model",
    description:
      "Rafailov et al. Treats the LM itself as the reward. Default alignment recipe in open fine-tunes through 2025; 2026 often mixed with GRPO for reasoners.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/2305.18290",
    paper_url: "https://arxiv.org/abs/2305.18290",
    categories: ["research"],
    techniques: ["rlhf"],
    features: ["No RM", "Preference pairs", "Stable open-source"],
    pricing: "—",
    catalog_weight: 80,
    aliases: ["dpo", "direct preference"],
    trend: 0.0,
  },
  {
    id: "grpo",
    kind: "technique",
    name: "GRPO",
    tagline: "Group relative policy optimization — the DeepSeek-R1 post-training trick",
    description:
      "Relative advantages inside a group of samples, no value model. What made R1-style reasoners trainable on a budget. Unsloth and TRL shipped recipes; every lab now has a variant.",
    license: "research",
    vendor: "DeepSeek",
    website: "https://arxiv.org/abs/2402.03300",
    paper_url: "https://arxiv.org/abs/2402.03300",
    categories: ["research"],
    techniques: ["rlhf", "test-time-compute"],
    features: ["Group baselines", "No critic", "Reasoning RL"],
    pricing: "—",
    catalog_weight: 84,
    aliases: ["grpo", "group relative"],
    trend: 1.2,
  },
  {
    id: "test-time-compute",
    kind: "technique",
    name: "Test-time compute",
    tagline: "Spend tokens at inference — think longer instead of only training bigger",
    description:
      "The 2025–26 scaling axis. o-series, Opus thinking, Grok reasoning, DeepSeek-R1 traces. Search, verification, and longer chains beat another 2× parameters for many hard tasks.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/2408.03314",
    paper_url: "https://arxiv.org/abs/2408.03314",
    categories: ["research"],
    techniques: ["chain-of-thought"],
    features: ["Thinking traces", "Effort sliders", "Self-consistency"],
    pricing: "—",
    catalog_weight: 93,
    aliases: ["test-time compute", "test time compute", "inference scaling", "thinking"],
    trend: 1.5,
  },
  {
    id: "speculative-decoding",
    kind: "technique",
    name: "Speculative decoding",
    tagline: "Draft with a small model, verify with the large one",
    description:
      "Leviathan et al. The serving trick behind many ‘fast’ modes. Medusa, EAGLE, and built-in draft models in vLLM/SGLang. Free speed when the draft is good.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/2211.17192",
    paper_url: "https://arxiv.org/abs/2211.17192",
    categories: ["infra"],
    techniques: [],
    features: ["Draft/verify", "Lossless", "EAGLE/Medusa"],
    pricing: "—",
    catalog_weight: 76,
    aliases: ["speculative decoding", "speculative-decoding"],
    trend: 0.3,
  },
  {
    id: "flash-attention",
    kind: "technique",
    name: "Flash Attention",
    tagline: "IO-aware exact attention — the kernel every trainer depends on",
    description:
      "Dao et al. Tiles attention to SRAM. FlashAttention-3 on Hopper/Blackwell is table stakes for training and long-context serving.",
    license: "open-source",
    vendor: "Dao-AILab",
    website: "https://github.com/Dao-AILab/flash-attention",
    github: "https://github.com/Dao-AILab/flash-attention",
    paper_url: "https://arxiv.org/abs/2205.14135",
    categories: ["infra"],
    techniques: [],
    features: ["IO-aware", "Exact", "FA3"],
    pricing: "Free",
    catalog_weight: 82,
    aliases: ["flash attention", "flashattention", "fa3"],
    trend: 0.2,
  },
  {
    id: "quantization",
    kind: "technique",
    name: "Quantization",
    tagline: "GGUF, AWQ, GPTQ, FP8 — same model, fewer bits",
    description:
      "How local AI exists. GGUF for llama.cpp, AWQ/GPTQ for vLLM, FP8 for frontier serving. Quality cliffs are real below 4-bit for hard reasoning.",
    license: "research",
    vendor: "",
    website: "https://github.com/ggml-org/llama.cpp",
    categories: ["local", "infra"],
    techniques: [],
    features: ["GGUF", "AWQ", "GPTQ", "FP8"],
    pricing: "—",
    catalog_weight: 87,
    aliases: ["quantization", "gguf", "awq", "gptq", "int4", "fp8"],
    trend: 0.3,
  },
  {
    id: "tool-use",
    kind: "technique",
    name: "Tool use / function calling",
    tagline: "Structured calls out to APIs, files, browsers, and MCP servers",
    description:
      "The difference between a chatbot and an agent. JSON schemas, MCP, computer use. Frontier rankings in 2026 are mostly tool-use rankings.",
    license: "research",
    vendor: "",
    website: "https://modelcontextprotocol.io",
    categories: ["agents"],
    techniques: [],
    features: ["JSON schemas", "MCP", "Parallel tools", "Computer use"],
    pricing: "—",
    catalog_weight: 94,
    aliases: ["tool use", "function calling", "tools", "function-calling"],
    trend: 1.3,
  },
  {
    id: "computer-use",
    kind: "technique",
    name: "Computer use",
    tagline: "See the screen, move the mouse, type — agents on a real desktop",
    description:
      "Anthropic computer use, OpenAI operators, and open CUAs. Claude Code and Cowork productized it. Fragile, powerful, and the 2026 demo that actually closes tickets.",
    license: "research",
    vendor: "",
    website: "https://www.anthropic.com/news/computer-use",
    categories: ["agents"],
    techniques: ["tool-use"],
    features: ["Screenshot loop", "Mouse/keyboard", "Desktop agents"],
    pricing: "—",
    catalog_weight: 85,
    aliases: ["computer use", "computer-use", "cua", "operator"],
    trend: 1.6,
  },
  {
    id: "multi-agent",
    kind: "technique",
    name: "Multi-agent",
    tagline: "Specialist roles, a graph, and a protocol instead of one giant prompt",
    description:
      "Crews, graphs, swarms. Works when roles are truly different and the protocol is strict; fails as expensive theatre when it is a single task in a trench coat.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/2308.08155",
    categories: ["agents"],
    techniques: ["tool-use", "react-pattern"],
    features: ["Role split", "Handoffs", "Critic/actor", "Swarm"],
    pricing: "—",
    catalog_weight: 82,
    aliases: ["multi-agent", "multi agent", "swarm", "crew"],
    trend: 0.8,
  },
  {
    id: "react-pattern",
    kind: "technique",
    name: "ReAct",
    tagline: "Reason + act in a loop — the original agent skeleton",
    description:
      "Yao et al. Thought, action, observation. Still the mental model under LangGraph nodes and every ‘agent’ tutorial. Simple, inspectable, easy to over-loop.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/2210.03629",
    paper_url: "https://arxiv.org/abs/2210.03629",
    categories: ["agents"],
    techniques: ["tool-use", "chain-of-thought"],
    features: ["Thought/act/obs", "Inspectable", "Tool loop"],
    pricing: "—",
    catalog_weight: 80,
    aliases: ["react", "reason+act", "reason and act"],
    trend: 0.1,
  },
  {
    id: "chain-of-thought",
    kind: "technique",
    name: "Chain of thought",
    tagline: "Make the model show (or hide) intermediate reasoning",
    description:
      "Wei et al. The parent of test-time compute. Hidden vs visible traces, self-consistency, and tree-of-thoughts all sit on this idea.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/2201.11903",
    paper_url: "https://arxiv.org/abs/2201.11903",
    categories: ["research"],
    techniques: [],
    features: ["Intermediate steps", "Self-consistency", "ToT"],
    pricing: "—",
    catalog_weight: 88,
    aliases: ["chain of thought", "cot", "chain-of-thought", "tree of thought"],
    trend: 0.4,
  },
  {
    id: "constitutional-ai",
    kind: "technique",
    name: "Constitutional AI",
    tagline: "Critique and revise against a written constitution — Anthropic’s alignment stack",
    description:
      "Bai et al. RLAIF against principles instead of only human labels. Still the philosophical and product core of Claude, including later classifier layers.",
    license: "research",
    vendor: "Anthropic",
    website: "https://www.anthropic.com/research/constitutional-ai-harmlessness-from-ai-feedback",
    paper_url: "https://arxiv.org/abs/2212.08073",
    categories: ["research"],
    techniques: ["rlhf"],
    features: ["Principles", "RLAIF", "Critique/revise"],
    pricing: "—",
    catalog_weight: 78,
    aliases: ["constitutional ai", "constitutional-ai", "rlaif"],
    trend: 0.2,
  },
  {
    id: "distillation",
    kind: "technique",
    name: "Distillation",
    tagline: "Train a small model to imitate a large one’s traces",
    description:
      "How DeepSeek-R1-distill, Gemma, and on-device models exist. 2026 trick: distill reasoning traces, not just answers. The cost-control valve for every lab.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/1503.02531",
    categories: ["infra", "open-models"],
    techniques: [],
    features: ["Teacher/student", "Trace distillation", "On-device"],
    pricing: "—",
    catalog_weight: 83,
    aliases: ["distillation", "distill", "synthetic data"],
    trend: 0.7,
  },
  {
    id: "prefix-caching",
    kind: "technique",
    name: "Prefix / prompt caching",
    tagline: "Reuse the KV cache for long, stable prefixes",
    description:
      "Anthropic, OpenAI, Gemini, and vLLM all cache the unchanging system+doc prefix. Turns 100K-token agents from ruinous to merely expensive.",
    license: "research",
    vendor: "",
    website: "https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching",
    categories: ["infra"],
    techniques: [],
    features: ["KV reuse", "System-prompt cache", "Cheaper agents"],
    pricing: "—",
    catalog_weight: 81,
    aliases: ["prompt caching", "prefix caching", "kv cache"],
    trend: 0.5,
  },
  {
    id: "diffusion",
    kind: "technique",
    name: "Diffusion",
    tagline: "Iterative denoising — still how most images and videos are made",
    description:
      "From DDPM through latent diffusion, flow-matching, and video DiTs. FLUX, Midjourney, Kling, Veo, Sora all sit on this family even when they market a new name.",
    license: "research",
    vendor: "",
    website: "https://arxiv.org/abs/2006.11239",
    paper_url: "https://arxiv.org/abs/2006.11239",
    categories: ["image", "video"],
    techniques: [],
    features: ["Denoising", "Latent", "Flow matching", "DiT"],
    pricing: "—",
    catalog_weight: 89,
    aliases: ["diffusion", "dit", "flow matching", "stable diffusion"],
    trend: 0.3,
  },

  // —— Workflows ————————————————————————————————————————————
  {
    id: "spec-driven-coding",
    kind: "workflow",
    name: "Spec-driven coding",
    tagline: "Write the spec, then let Claude Code / Cursor / Codex execute against it",
    description:
      "The 2026 professional loop: a human writes constraints and tests, an agent implements, another pass reviews the diff. Plan mode first; never one-shot a repo.",
    license: "mixed",
    vendor: "",
    website: "",
    categories: ["coding", "agents"],
    techniques: ["tool-use", "test-time-compute", "computer-use", "multi-agent"],
    features: ["Plan then act", "Tests as spec", "Diff review", "MCP tools"],
    pricing: "—",
    catalog_weight: 88,
    aliases: ["spec driven", "plan mode", "agentic coding"],
    trend: 1.4,
  },
  {
    id: "local-llm-stack",
    kind: "workflow",
    name: "Local LLM stack",
    tagline: "Ollama or llama.cpp + Open WebUI/LM Studio, GGUF models, no cloud",
    description:
      "The frugal privacy stack. Qwen/Llama/DeepSeek quantised, RAG on disk, MCP to local files. Quality trails frontier closed models; cost and data stay at home.",
    license: "open-source",
    vendor: "",
    website: "https://ollama.com",
    categories: ["local"],
    techniques: ["quantization", "rag", "tool-use"],
    features: ["GGUF", "Air-gap option", "Open WebUI", "MCP"],
    pricing: "Electricity + weights",
    catalog_weight: 84,
    aliases: ["local llm", "local stack", "self hosted llm"],
    trend: 0.6,
  },
  {
    id: "production-rag",
    kind: "workflow",
    name: "Production RAG",
    tagline: "Parse, chunk, hybrid retrieve, rerank, cite, eval — then loop",
    description:
      "LlamaParse or equivalent, hybrid BM25+vectors (Qdrant/pgvector), a reranker, forced citations, Promptfoo/LangSmith evals on a golden set. Agentic RAG only after the naive path has metrics.",
    license: "mixed",
    vendor: "",
    website: "",
    categories: ["data", "eval"],
    techniques: ["rag", "agentic-rag", "quantization"],
    features: ["Hybrid search", "Rerank", "Citations", "Golden evals"],
    pricing: "—",
    catalog_weight: 86,
    aliases: ["production rag", "rag pipeline"],
    trend: 0.4,
  },
  {
    id: "research-agent",
    kind: "workflow",
    name: "Research agent",
    tagline: "Perplexity + arXiv + NotebookLM — generate elsewhere, verify here",
    description:
      "Lookup in Perplexity, primary papers from arXiv, corpus briefing in NotebookLM, synthesis in Claude Fable or GPT. Never one model for both claim and citation.",
    license: "mixed",
    vendor: "",
    website: "",
    categories: ["research", "search"],
    techniques: ["rag", "tool-use", "chain-of-thought"],
    features: ["Citations", "Primary sources", "Audio briefings"],
    pricing: "—",
    catalog_weight: 82,
    aliases: ["research agent", "deep research"],
    trend: 0.5,
  },
  {
    id: "eval-harness",
    kind: "workflow",
    name: "Eval harness",
    tagline: "Golden sets in git, Promptfoo in CI, traces in LangSmith or Phoenix",
    description:
      "The thing that separates a demo from a product. Offline assertions on every prompt change; sampled online traces; red-team plugins before launch.",
    license: "mixed",
    vendor: "",
    website: "https://www.promptfoo.dev",
    categories: ["eval"],
    techniques: ["rag"],
    features: ["CI gates", "Golden sets", "Red team", "Traces"],
    pricing: "—",
    catalog_weight: 80,
    aliases: ["eval harness", "llm eval", "evals"],
    trend: 0.6,
  },
  {
    id: "fine-tune-loop",
    kind: "workflow",
    name: "Fine-tune loop",
    tagline: "Unsloth LoRA on a domain set, eval, distill, deploy GGUF or vLLM",
    description:
      "Collect traces → filter → QLoRA with Unsloth → Promptfoo vs the base → merge or keep adapters → serve with vLLM or llama.cpp. GRPO only if you have a verifiable reward.",
    license: "open-source",
    vendor: "",
    website: "https://unsloth.ai",
    categories: ["open-models", "infra"],
    techniques: ["lora", "quantization", "grpo", "distillation"],
    features: ["Single-GPU", "Adapters", "Eval gate", "Local serve"],
    pricing: "—",
    catalog_weight: 79,
    aliases: ["fine-tune", "finetune", "qlora workflow"],
    trend: 0.5,
  },
  {
    id: "multi-model-router",
    kind: "workflow",
    name: "Multi-model router",
    tagline: "Cheap model first, frontier on hard tasks, OpenRouter as the switchboard",
    description:
      "Classify the task, send boilerplate to DeepSeek/Qwen/Groq, escalate coding to Opus 5 or Grok 4.6, writing to Fable. Cache prefixes. Cap spend. Log every route.",
    license: "mixed",
    vendor: "",
    website: "https://openrouter.ai",
    categories: ["infra"],
    techniques: ["prefix-caching", "distillation"],
    features: ["Escalation", "Fallbacks", "Cost caps", "Traces"],
    pricing: "—",
    catalog_weight: 83,
    aliases: ["model router", "routing", "fallback"],
    trend: 0.8,
  },
  {
    id: "comfy-pipeline",
    kind: "workflow",
    name: "ComfyUI production pipeline",
    tagline: "Versioned graphs, FLUX/video checkpoints, batch out to a review folder",
    description:
      "Treat image/video like software: a checked-in graph, pinned checkpoints, IP-Adapter for brand, and a human review step. Midjourney for taste exploration, Comfy for the run.",
    license: "open-source",
    vendor: "",
    website: "https://github.com/comfyanonymous/ComfyUI",
    categories: ["image", "video"],
    techniques: ["diffusion", "lora"],
    features: ["Versioned graphs", "Brand adapters", "Batch", "Review"],
    pricing: "—",
    catalog_weight: 75,
    aliases: ["comfy pipeline", "image pipeline"],
    trend: 0.3,
  },

  // —— Canonical papers ————————————————————————————————————
  {
    id: "attention-is-all-you-need",
    kind: "paper",
    name: "Attention Is All You Need",
    tagline: "Vaswani et al., 2017 — the transformer paper",
    description:
      "Introduced the transformer. Still the most-cited foundation of the industry. Everything else in this atlas is a footnote.",
    license: "research",
    vendor: "Google Brain",
    website: "https://arxiv.org/abs/1706.03762",
    paper_url: "https://arxiv.org/abs/1706.03762",
    categories: ["research"],
    techniques: ["transformer"],
    features: ["arXiv:1706.03762"],
    pricing: "—",
    catalog_weight: 99,
    aliases: ["attention is all you need", "vaswani 2017"],
    trend: 0.0,
  },
  {
    id: "instructgpt",
    kind: "paper",
    name: "Training language models to follow instructions with human feedback",
    tagline: "Ouyang et al., 2022 — InstructGPT / RLHF",
    description:
      "The paper that turned base models into assistants. RLHF recipe that ChatGPT productized months later.",
    license: "research",
    vendor: "OpenAI",
    website: "https://arxiv.org/abs/2203.02155",
    paper_url: "https://arxiv.org/abs/2203.02155",
    categories: ["research"],
    techniques: ["rlhf"],
    features: ["arXiv:2203.02155"],
    pricing: "—",
    catalog_weight: 90,
    aliases: ["instructgpt", "ouyang"],
    trend: 0.0,
  },
  {
    id: "lora-paper",
    kind: "paper",
    name: "LoRA: Low-Rank Adaptation of Large Language Models",
    tagline: "Hu et al., 2021 — the fine-tune that fits on one GPU",
    description:
      "Low-rank adapters. Without this paper the open fine-tune ecosystem does not exist.",
    license: "research",
    vendor: "Microsoft",
    website: "https://arxiv.org/abs/2106.09685",
    paper_url: "https://arxiv.org/abs/2106.09685",
    categories: ["research"],
    techniques: ["lora"],
    features: ["arXiv:2106.09685"],
    pricing: "—",
    catalog_weight: 86,
    aliases: ["lora paper", "hu lora"],
    trend: 0.0,
  },
];
