/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DistributeRouteImport } from './routes/distribute'
import { Route as DriftRouteImport } from './routes/drift'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as IraRouteImport } from './routes/ira'
import { Route as LensRouteImport } from './routes/lens'
import { Route as MethodRouteImport } from './routes/method'
import { Route as MethodsRouteImport } from './routes/methods'
import { Route as OgDotsvgRouteImport } from './routes/og[.]svg'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as RefusalsRouteImport } from './routes/refusals'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WeekRouteImport } from './routes/week'
import { Route as WeekDotmdRouteImport } from './routes/week[.]md'
import { Route as ApiAtlasDotjsonRouteImport } from './routes/api/atlas[.]json'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as ApiPublishRouteImport } from './routes/api/publish'
import { Route as ApiThreadDotjsonRouteImport } from './routes/api/thread[.]json'
import { Route as ESlugRouteImport } from './routes/e.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributeRoute = DistributeRouteImport.update({
  id: '/distribute',
  path: '/distribute',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftRoute = DriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IraRoute = IraRouteImport.update({
  id: '/ira',
  path: '/ira',
  getParentRoute: () => rootRouteImport,
} as any)
const LensRoute = LensRouteImport.update({
  id: '/lens',
  path: '/lens',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRoute = MethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotsvgRoute = OgDotsvgRouteImport.update({
  id: '/og.svg',
  path: '/og.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RefusalsRoute = RefusalsRouteImport.update({
  id: '/refusals',
  path: '/refusals',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekRoute = WeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekDotmdRoute = WeekDotmdRouteImport.update({
  id: '/week.md',
  path: '/week.md',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAtlasDotjsonRoute = ApiAtlasDotjsonRouteImport.update({
  id: '/api/atlas.json',
  path: '/api/atlas.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishRoute = ApiPublishRouteImport.update({
  id: '/api/publish',
  path: '/api/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreadDotjsonRoute = ApiThreadDotjsonRouteImport.update({
  id: '/api/thread.json',
  path: '/api/thread.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas': typeof AtlasRoute
  '/compare': typeof CompareRoute
  '/distribute': typeof DistributeRoute
  '/drift': typeof DriftRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/ira': typeof IraRoute
  '/lens': typeof LensRoute
  '/method': typeof MethodRoute
  '/methods': typeof MethodsRoute
  '/og.svg': typeof OgDotsvgRoute
  '/papers': typeof PapersRoute
  '/rankings': typeof RankingsRoute
  '/refusals': typeof RefusalsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/week': typeof WeekRoute
  '/week.md': typeof WeekDotmdRoute
  '/api/atlas.json': typeof ApiAtlasDotjsonRoute
  '/api/cron': typeof ApiCronRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/thread.json': typeof ApiThreadDotjsonRoute
  '/e/$slug': typeof ESlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas': typeof AtlasRoute
  '/compare': typeof CompareRoute
  '/distribute': typeof DistributeRoute
  '/drift': typeof DriftRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/ira': typeof IraRoute
  '/lens': typeof LensRoute
  '/method': typeof MethodRoute
  '/methods': typeof MethodsRoute
  '/og.svg': typeof OgDotsvgRoute
  '/papers': typeof PapersRoute
  '/rankings': typeof RankingsRoute
  '/refusals': typeof RefusalsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/week': typeof WeekRoute
  '/week.md': typeof WeekDotmdRoute
  '/api/atlas.json': typeof ApiAtlasDotjsonRoute
  '/api/cron': typeof ApiCronRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/thread.json': typeof ApiThreadDotjsonRoute
  '/e/$slug': typeof ESlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas': typeof AtlasRoute
  '/compare': typeof CompareRoute
  '/distribute': typeof DistributeRoute
  '/drift': typeof DriftRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/ira': typeof IraRoute
  '/lens': typeof LensRoute
  '/method': typeof MethodRoute
  '/methods': typeof MethodsRoute
  '/og.svg': typeof OgDotsvgRoute
  '/papers': typeof PapersRoute
  '/rankings': typeof RankingsRoute
  '/refusals': typeof RefusalsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/week': typeof WeekRoute
  '/week.md': typeof WeekDotmdRoute
  '/api/atlas.json': typeof ApiAtlasDotjsonRoute
  '/api/cron': typeof ApiCronRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/thread.json': typeof ApiThreadDotjsonRoute
  '/e/$slug': typeof ESlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atlas'
    | '/compare'
    | '/distribute'
    | '/drift'
    | '/feed.xml'
    | '/ira'
    | '/lens'
    | '/method'
    | '/methods'
    | '/og.svg'
    | '/papers'
    | '/rankings'
    | '/refusals'
    | '/robots.txt'
    | '/signals'
    | '/sitemap.xml'
    | '/week'
    | '/week.md'
    | '/api/atlas.json'
    | '/api/cron'
    | '/api/publish'
    | '/api/thread.json'
    | '/e/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atlas'
    | '/compare'
    | '/distribute'
    | '/drift'
    | '/feed.xml'
    | '/ira'
    | '/lens'
    | '/method'
    | '/methods'
    | '/og.svg'
    | '/papers'
    | '/rankings'
    | '/refusals'
    | '/robots.txt'
    | '/signals'
    | '/sitemap.xml'
    | '/week'
    | '/week.md'
    | '/api/atlas.json'
    | '/api/cron'
    | '/api/publish'
    | '/api/thread.json'
    | '/e/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atlas'
    | '/compare'
    | '/distribute'
    | '/drift'
    | '/feed.xml'
    | '/ira'
    | '/lens'
    | '/method'
    | '/methods'
    | '/og.svg'
    | '/papers'
    | '/rankings'
    | '/refusals'
    | '/robots.txt'
    | '/signals'
    | '/sitemap.xml'
    | '/week'
    | '/week.md'
    | '/api/atlas.json'
    | '/api/cron'
    | '/api/publish'
    | '/api/thread.json'
    | '/e/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtlasRoute: typeof AtlasRoute
  CompareRoute: typeof CompareRoute
  DistributeRoute: typeof DistributeRoute
  DriftRoute: typeof DriftRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  IraRoute: typeof IraRoute
  LensRoute: typeof LensRoute
  MethodRoute: typeof MethodRoute
  MethodsRoute: typeof MethodsRoute
  OgDotsvgRoute: typeof OgDotsvgRoute
  PapersRoute: typeof PapersRoute
  RankingsRoute: typeof RankingsRoute
  RefusalsRoute: typeof RefusalsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignalsRoute: typeof SignalsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeekRoute: typeof WeekRoute
  WeekDotmdRoute: typeof WeekDotmdRoute
  ApiAtlasDotjsonRoute: typeof ApiAtlasDotjsonRoute
  ApiCronRoute: typeof ApiCronRoute
  ApiPublishRoute: typeof ApiPublishRoute
  ApiThreadDotjsonRoute: typeof ApiThreadDotjsonRoute
  ESlugRoute: typeof ESlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribute': {
      id: '/distribute'
      path: '/distribute'
      fullPath: '/distribute'
      preLoaderRoute: typeof DistributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift': {
      id: '/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof DriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ira': {
      id: '/ira'
      path: '/ira'
      fullPath: '/ira'
      preLoaderRoute: typeof IraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lens': {
      id: '/lens'
      path: '/lens'
      fullPath: '/lens'
      preLoaderRoute: typeof LensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.svg': {
      id: '/og.svg'
      path: '/og.svg'
      fullPath: '/og.svg'
      preLoaderRoute: typeof OgDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refusals': {
      id: '/refusals'
      path: '/refusals'
      fullPath: '/refusals'
      preLoaderRoute: typeof RefusalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week': {
      id: '/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof WeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week.md': {
      id: '/week.md'
      path: '/week.md'
      fullPath: '/week.md'
      preLoaderRoute: typeof WeekDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/atlas.json': {
      id: '/api/atlas.json'
      path: '/api/atlas.json'
      fullPath: '/api/atlas.json'
      preLoaderRoute: typeof ApiAtlasDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish': {
      id: '/api/publish'
      path: '/api/publish'
      fullPath: '/api/publish'
      preLoaderRoute: typeof ApiPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/thread.json': {
      id: '/api/thread.json'
      path: '/api/thread.json'
      fullPath: '/api/thread.json'
      preLoaderRoute: typeof ApiThreadDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtlasRoute: AtlasRoute,
  CompareRoute: CompareRoute,
  DistributeRoute: DistributeRoute,
  DriftRoute: DriftRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  IraRoute: IraRoute,
  LensRoute: LensRoute,
  MethodRoute: MethodRoute,
  MethodsRoute: MethodsRoute,
  OgDotsvgRoute: OgDotsvgRoute,
  PapersRoute: PapersRoute,
  RankingsRoute: RankingsRoute,
  RefusalsRoute: RefusalsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignalsRoute: SignalsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeekRoute: WeekRoute,
  WeekDotmdRoute: WeekDotmdRoute,
  ApiAtlasDotjsonRoute: ApiAtlasDotjsonRoute,
  ApiCronRoute: ApiCronRoute,
  ApiPublishRoute: ApiPublishRoute,
  ApiThreadDotjsonRoute: ApiThreadDotjsonRoute,
  ESlugRoute: ESlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
