/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DriftRouteImport } from './routes/drift'
import { Route as LensRouteImport } from './routes/lens'
import { Route as MethodsRouteImport } from './routes/methods'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as ESlugRouteImport } from './routes/e.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftRoute = DriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const LensRoute = LensRouteImport.update({
  id: '/lens',
  path: '/lens',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRoute = MethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/compare': typeof CompareRoute
  '/drift': typeof DriftRoute
  '/lens': typeof LensRoute
  '/methods': typeof MethodsRoute
  '/papers': typeof PapersRoute
  '/rankings': typeof RankingsRoute
  '/signals': typeof SignalsRoute
  '/api/cron': typeof ApiCronRoute
  '/e/$slug': typeof ESlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/compare': typeof CompareRoute
  '/drift': typeof DriftRoute
  '/lens': typeof LensRoute
  '/methods': typeof MethodsRoute
  '/papers': typeof PapersRoute
  '/rankings': typeof RankingsRoute
  '/signals': typeof SignalsRoute
  '/api/cron': typeof ApiCronRoute
  '/e/$slug': typeof ESlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/compare': typeof CompareRoute
  '/drift': typeof DriftRoute
  '/lens': typeof LensRoute
  '/methods': typeof MethodsRoute
  '/papers': typeof PapersRoute
  '/rankings': typeof RankingsRoute
  '/signals': typeof SignalsRoute
  '/api/cron': typeof ApiCronRoute
  '/e/$slug': typeof ESlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/compare'
    | '/drift'
    | '/lens'
    | '/methods'
    | '/papers'
    | '/rankings'
    | '/signals'
    | '/api/cron'
    | '/e/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/compare'
    | '/drift'
    | '/lens'
    | '/methods'
    | '/papers'
    | '/rankings'
    | '/signals'
    | '/api/cron'
    | '/e/$slug'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/compare'
    | '/drift'
    | '/lens'
    | '/methods'
    | '/papers'
    | '/rankings'
    | '/signals'
    | '/api/cron'
    | '/e/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  CompareRoute: typeof CompareRoute
  DriftRoute: typeof DriftRoute
  LensRoute: typeof LensRoute
  MethodsRoute: typeof MethodsRoute
  PapersRoute: typeof PapersRoute
  RankingsRoute: typeof RankingsRoute
  SignalsRoute: typeof SignalsRoute
  ApiCronRoute: typeof ApiCronRoute
  ESlugRoute: typeof ESlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift': {
      id: '/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof DriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lens': {
      id: '/lens'
      path: '/lens'
      fullPath: '/lens'
      preLoaderRoute: typeof LensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  CompareRoute: CompareRoute,
  DriftRoute: DriftRoute,
  LensRoute: LensRoute,
  MethodsRoute: MethodsRoute,
  PapersRoute: PapersRoute,
  RankingsRoute: RankingsRoute,
  SignalsRoute: SignalsRoute,
  ApiCronRoute: ApiCronRoute,
  ESlugRoute: ESlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
